### ISSUE TITLE
Disk/NFS Mounting Service

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#10]
In discussions with the OPS team, we currently mount a number of NFS volumes. So when we mount disks, it must support NFS, and it must support special options that you'd specify on the command line.

I've asked our operations team for output from `/etc/fstab`, and will post that here once I get it. That should allow us to fully understand the requirements.

**Comment by jeffaco** [comment]
Here's a sample [/etc/fstab](https://gist.github.com/jeffaco/e9edb44d9a75ec30da331b006bb401b7) file used in our data centers for NFS (ignore the RedHat part, it's here for completeness).

While the operations folks told me that each mount point needs special options to be set, I don't see this from [this file](https://gist.github.com/jeffaco/e9edb44d9a75ec30da331b006bb401b7). So I think he misunderstood my question. That said, it wouldn't hurt to have something "basic" for options (not validated, just passed along to "mount" as is). But I'll leave that to you.

The basic `mount` command for NFS is something like this:

```
mount -F nfs [-o mount-options] server:/directory /mount-point
```

Currently, the [YAML Specification](https://gist.github.com/jeffaco/9664aa4a4e5620e7ee16c8405be03a4a) has this for disks:

```
storage:
    -
      device: "/vol/bar"
      mount: "/mnt/bar"
      size: "30G"
      path: "/dev/1234567890"
      path: "/dev/2345678901"
    -
      device: "/vol/foo"
      mount: "/mnt/foo"
      size: "112G"
```

I understand `device` and `mount` tags. Does the `size` tag map into `rsize`/`wsize` in the fstab?

What's the purpose of the `path` tags in the first YAML segment?

```
      path: "/dev/1234567890"
      path: "/dev/2345678901"
```

How's this first a first stab proposition for a `storage` segment:

```
      file_system: nfs
      device: "a:b:c:d:/nfs/share"
      mount: "/mnt/foo"
      size: "112G"
      options: "<passed as is, if specified>"
```

Thoughts/feedback appreciated. I want something flexible to mount disks if we needed to (via the NetApp), which I think we have if with an appropriate `file_system` if `device` is `/dev/mapper/xxxxxxxx`. But we primarily use NFS most of the time.

**Comment by schaefi** [comment]
Finally some clarification on what the storage section should be good for. Thanks much

I like your suggestion but I think the size: key is of no interest. We can mount the location but size constraints will have no effect. Thus I suggest a slightly changed structure

```yaml
storage:
  -
    file_system: nfs
    device: "10.250.21.12:/nfs/share"
    mount: "/mnt/foo"
    options:
        - a
        - b
        - c
```

**Comment by schaefi** [comment]
>Given that we use NFS most of the time, I guess we have a dependency that the network must be up >and operational before the storage segment is processed.

agreed

**Comment by schaefi** [comment]
I also suggest the storage services operates in a way that it adds entries to the existing fstab file and only calls:

```
mount -a
```

which will mount all not yet mounted targets to the system. That way the locations are configured correctly and can be managed like any other mount target. Given the cleanup service will delete all traces of azure-li-services having them in fstab is probably a requirement

**Comment by rjschwei** [comment]
Agreed with adding things to the fstab file.

The intention of having the size in the YAML was always for verification purposes and I would strongly suggest to keep it and verify it. If, for whatever reason a bug/mistake happens when the storage is presented and the YAML has a mismatch with what we actually expect we can at least complain. I guess an example is in order.

Lets say the user requests a certain size system and for that system the DB storage is expected to 20TB. However for whatever reason filesystems get switched up on the NetApp side and we end up with a 20GB system. The automation "blindly" mounts the storage device that is now only 20GB to the location where HANA expects its DB storage. Now we are going to let the user go through the HANA setup, which is time consuming and do whatever they do only to find out that as soon as they turn on HANA they are going to run out of storage space in no time. Now we are going to have a support ticket and problem that requires manual intervention or at worst requires the user to start form scratch.

IMHO the cost of adding the expected size to the YAML and verifying it is cheap and well worth the effort when compared to the consequences a simple typo or mis-configuration can have.

**Comment by schaefi** [comment]
ok I agree, did not thought of the possibility that the nfs share could be too small. Makes all sense to can we finalize on:

```yaml
storage:
  -
    file_system: nfs
    min_size:  112G
    device: "10.250.21.12:/nfs/share"
    mount: "/mnt/foo"
    options:
        - a
        - b
        - c
```
