### ISSUE TITLE
Cleanup of the YAML file

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#14]
The [YAML file](https://gist.github.com/jeffaco/9664aa4a4e5620e7ee16c8405be03a4a), when I started, was adopted from others. As it's being developed, I note that there are fields in there that serve no purpose.

1. `version:` date field. We have no versioning, but the schema should allow for that. Do we want a date field, or a number here (like `version: 1`)? We should go on ignoring it for now, but let the field remain in case we need it at a future time.

1. `blade:` entry (with fields under it). I'm not sure that this serves a purpose at all, but removal will result in code changes for both of us. Remove?

1. `sku:` is a placeholder field for us. [azure-li-services](https://github.com/SUSE/azure-li-services) will ignore it, but we'll continue to specify that.

1. `cpu:` is ignored right now. This could serve as a minimum (much like `min_size` under storage), but seems redundant given that `sku` has that. Remove?

1. `memory` is ignored right now. Same as `cpu`, remove?

1. `time_server`. Our colos don't have a time server. If one was set up, that would be customer specific, and wouldn't be something that would be generally offered (so customer would need to set that up). Remove?

Since all of this predates me, I'm going to reach out to my team and get feedback on these issues. I don't want to remove something that might be important for some reason I'm unaware of.

**Comment by jeffaco** [comment]
For the latest and greatest YAML file, see [here](https://gist.github.com/jeffaco/9664aa4a4e5620e7ee16c8405be03a4a). This issue specifically refers to revision 7, dated 05/30/2018.

**Comment by lagalbra** [comment]
My comments:

- SKU should be among [this set](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/hanaonazure/resource-manager/Microsoft.HanaOnAzure/preview/2017-11-03-preview/hanaonazure.json#L309)
  - If you want to correlate that data with memory/CPU specs, see Microsoft documentation [here](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-overview-architecture)
  - I am inclined to agree that either the SKU or the CPU/memory should be removed; having both is redundant. Depending on your use of the SKU/specs will determine which of the two you should keep.

**Comment by rjschwei** [comment]
version: -> we should keep this in case there is ever an incompatible change. IMHO it should be set to a date code such as "version: 20180530". This code should reflect the date when we are "done" with the YAML and then the code should check the version:
`if not config.version <= 20180530:
  raise AzureLIYamlVersionException()`

blade: -> initially intended to describe the system so we can verify the system before doing stuff. Similar to using "size:" in the "storage:" section. I'd say keep "blade" but move "storage:" one level up, i.e. "storeage" is not a sub-section of "blade:

sku: -> immaterial to SUSE code

cpu: & memory: -> should both be used for verification purposes similar to "size:" for storage. From our perspective this is not synonymous with "sku:" as we'd have to hardcode the sku to have som translation table for verification. skus change so any such translation table in the code would not be a good idea.

time_server: As long as the platform does not provide a time server, I agree that this is not needed.

**Comment by abhinababasu** [comment]
Version is a date because that's what is used in Azure APIs (also in AWS). So prior art and we need to be in sync with this. Also in general I believe in date based versioning. Because you can actually tell how stable or how much evolution is happening.

I think we need to remove instance_type. The reason is that this distinction is largely internal implementation based and will soon make little sense as we will have the largest VM eat into LI sizes and the largest LI eating into VLI sizes. There will be overlap at the boundary as well. So it should all be SKU defined and the SKU should indicate internally which is what.

+1 on @lagalbra comments. The sku should match the json she pointed.

Remove CPU because the SKU directly tells you that. SR92 is 92 CPU threads. Sae with memory. All of these are derivable from the SKU number.

Remove time_server.

According to history of this file, we defined it early on, when we were still not sure where it will finally land. So if things don't make sense, remove at will :)

**Comment by schaefi** [comment]
concerning instance_type we currently use it in the network service as we know network will be different (vswitch vs. bridge) which requires different setup but is based on the same setup data. In general it would be good for us to know the instance type if their hardware is different as we operate on the system level were this matters

**Comment by jeffaco** [comment]
Yes, `instance_type` was added once I recognized that networking setup on VLI is **very** different than on LI platforms. So we needed a way to differentiate the two.

If it turns out, in VLI, that there are other differences, we still may keep the distinction (not as a size thing, but as a *UCS* is different from *HPE*.

I propose we leave that for now, but be open in the future if details dictate a change. In the short term, though, that will be used to determine how networking is configured.

**Comment by jeffaco** [comment]
How's this as a first stab for cleanup of the YAML file?

```
version: 2017-11-15
instance_type: LargeInstance|VeryLargeInstance
sku: "SR92"

networking:
  -
    interface: eth0
    vlan: 10
    ip: 10.250.10.51
    gateway: 10.250.10.1
    subnet_mask: 255.255.255.0
  -
    interface: eth1
    vlan: 51
    ip: 10.250.51.51
    subnet_mask: 255.255.255.0
  -
    interface: eth2
    vlan: 52
    ip: 10.250.52.51
    subnet_mask: 255.255.255.0

storage:
  -
    file_system: nfs
    min_size:  112G
    device: "10.250.21.12:/nfs/share"
    mount: "/mnt/foo"
    mount_options:
      - a
      - b
      - c

credentials:
  username: "hanauser"
  shadow_hash: $6...
  ssh-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCt0tiRjcZE0XU38M6aBxaRd+fsVUnezP8/fStL4vgxuzu84FFTTK6XIVsMWVbDxROVA0H98Sexfm8ZDgxYxQ5g6Nk1wbWxB9wbPHrykJScV3tUGWh4RgDq4rm/8+k7Msd32Ubj2t5962W1h1s+zhax4io0bSvJtKj9Ke1Bcq86zEcFg3iPIyxSY8oKK02luT3m73/0L+2BzVXzSsUwE23Nh37+jVAWt+aXHJPlg7YNJGN/9luqx90I3BiPDRtsj4AZ8OtYvBgpDbGK8cVMEDGvOg0+a8JE8oebzgzArYNlWskCRvdvVPU3rk8GKjSKDC2j5lS5sjiiT342Qc3VjoScg5pNfT5fBQ2KI3+LQW9UGwtQwX4er+rjVMM72f1BRI5pIBuwWQIQJzwlqF/KUZcCC5Ly8H8S96thxpmsnXz89GOfldFbQQa/IP5dqCERFpncg1stnDjtGUGU7LIBcBkxqC0ixHgsNKlqFkpT/2oP3y8J875sxykKcigq2Gzw8avXH0W/7nA2pGIrqMMNvMs4ORmSi0FufwNnMsmJYW/baOPUgO+yzUeWLL9wajFo7ozoXz/Q1mLhd8791XO8+ph1Txs0smqV0BK7l/8rAOfhJB1t/aLIB1D+AuVxkfFXUDCcTT4LHSpS7LgI+vsegcN5rPPdFucgMoxLncEC5Fwfww== Jeff Coffler Common Key"

packages:
  repository_name: azure_packages
    - "/directory-with-rpm-files"
    - "/another-directory-with-rpm-files"

call: "path/in/LUN/update.sh"
```

This includes everything discussed so far. Compare that to existing [gist](https://gist.github.com/jeffaco/9664aa4a4e5620e7ee16c8405be03a4a) to see what's changed.

I did note that `credentials:` only allows for one credential to be created. That's consistent with Azure, and seems fine with me. Anybody have a problem with that? Does this need to be a list to allow for two or more sets of credentials?

**Comment by jeffaco** [comment]
Just to be clear, we don't expect you to do a sku to cpu/mem translation. Currently, the cpu/mem fields are totally ignored. I'm glad we're having this discussion!

Are you suggesting that we retain cpu/mem, and use them similarly to `storage:min_size` (warn us if the machine is undersized)? But oversized is as important as undersized. The onus is on us to deploy to the proper system, and I don't feel like you're responsible for insuring that.

Also, I'm not 100% sure what you'll do if you find a conflict. The machine is booting up (first boot). If the warning will just be buried in a log file, I'm not sure that's all that useful. Without a human (or another system) watching, where will these warnings be so that we can catch them?

Unrelated: Thanks for pointing out version format, updated [master gist](https://gist.github.com/jeffaco/9664aa4a4e5620e7ee16c8405be03a4a). I'll make every attempt, when merged, that this is retained.

**Comment by rjschwei** [comment]
> Are you suggesting that we retain cpu/mem

Yes

> and use them similarly to storage:min_size

Yes

> But oversized is as important as undersized. The onus is on us to deploy to the proper system,  and I don't feel like you're responsible for insuring that.

Yes it is Microsoft's responsibility to deploy to the right system, but mistakes, bugs, happen and we're here to help. As with the storage size the question is whether you want to deal with a customer that finds out that they are on the wrong system after they spent a month fine tuning and configuring all their HANA applications or if you'd rather find out earlier. I think earlier is better people tend to get ticked off when they have to redo things for reasons out of their control.

> Also, I'm not 100% sure what you'll do if you find a conflict.

We will simply not configure the system, or we can just setup the network and nothing else to allow for easy debugging. We'll simply write "CPU mismatch" or "Memory mismatch" as error message and then a simple "systemctl status azure-li-verify.service" will reveal the error.

**Comment by abhinababasu** [comment]
I am ok with mem/cpu/instance-type being retained if that is required. I understand SUSE code not wanting the mapping to be hard-coded. Our yaml generator (when we get to that), can easily spit out the instance type and cpu/mem from the SKU.

Api version across the board is becoming YYYY-MM-DD, I would like that it to remain so

**Comment by abhinababasu** [comment]
Single credential is preferred. Once customer can login they can make as many as they want

**Comment by jeffaco** [comment]
While API versioning in M/S software might be `YYYY-MM-DD`, this is sufficiently independent where I'm comfortable following SUSE's suggestion on this. It's not important enough to argue over.

With regards to minimum CPU/MEM requirements, I'm still not 100% sure what should be done if something goes wrong here:

1. You could not initialize (except for network) the system, but you'd also have to initialize credentials, or we couldn't log in. And we don't record the password the requester set up, and we certainly don't have the private key for the cert if the requester went for that.

1. This implies some sort of failure credential that is only set up if something goes wrong, but this seems sloppy.

1. Independent to all this, it would be nice to have a positive/negative verification that the system came up properly (without logging in). This is problematic due to VLAN restrictions, though. These systems, due to POST memory tests, take a very long time to boot (15+ minutes) ...

I guess I'd like to understand EXACTLY what will happen upon failure, and how we'd know about it. You can safely assume we do not have the password or private SSH key for the person requesting the box, so we'd need some other way to establish access (VLANs aside). Perhaps this does end up calling for a second account to be established that we have control over, but maybe which is only created in an error condition?

**Comment by schaefi** [comment]
> Single credential is preferred. Once customer can login they can make as many as they want

The users service as we implemented it allows for multiple accounts to be created. See this conversation where multiple accounts seemed to be needed by the operations team: https://github.com/SUSE/azure-li-services/issues/6

So credentials is a list, but you can go with just one entry

```yaml
credentials:
  -
    username: hanauser
    shadow_hash: ...
    ssh-key: ...
```

**Comment by schaefi** [comment]
> I'm still not 100% sure what should be done if something goes wrong here:

yes this is a good question and there is probably no ideal solution. From a system boot perspective we establish a dependency based workflow which is controlled by the systemd daemon. If something goes wrong we aim for a good error message to indicate fast and clear what happened. This information can be obtained by calling the systemctl utility which talks with systemd.

However to get that information you need to be logged in to the system in some way. This is the part we can't influence much. From an operations team perspective I could think of the following to work if we can assume the reading of the yaml file succeeded

* allow a less privileged user (not root) with a one time password you create at instance creating time. This setup could be put into the yaml file, e.g

   ```yaml
  credentials:
    -
      username: azure_troubleshoot
      shadow_hash: [random_and_valid_for_this_instance_during_lifetime]
   ```

   (we would have to update the users service such that it does not put the user on sudo)

* allow for a console access which is often done through an ipmi console or a serial terminal. login with the troubleshooting user would now be possible. 

Of course I'm not aware if that violates any policy between the parties. Thus just an idea

>Perhaps this does end up calling for a second account to be established that we have control over, >but maybe which is only created in an error condition?

This would require to know exactly what an error condition is. If this is limited to the code we write it would be no problem to let the cleanup service create a troubleshooting account, but I thought there is much more which could go wrong in the workload which does not directly trigger an error condition in our services.
