### ISSUE TITLE
User creation is not correct in image v1.0.30 (.ssh permissions)

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#37]
Multiple bugs here, but all related to user creation:

Given a YAML file containing this segment:

```
credentials:
 -
  username: "hanauser"
  shadow_hash: $6$/i4bVTW/Ec/0o.eU$6BFOeP9xn4ZqoDzYbBjuZZupe9VpiqAn9wrXHmZ.Rcyyl.AxQSzmja75OOupHAuzUQ1WaI8MIUqLKdavT252t/
  ssh-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCt0tiRjcZE0XU38M6aBxaRd+fsVUnezP8/fStL4vgxuzu84FFTTK6XIVsMWVbDxROVA0H98Sexfm8ZDgxYxQ5g6Nk1wbWxB9wbPHrykJScV3tUGWh4RgDq4rm/8+k7Msd32Ubj2t5962W1h1s+zhax4io0bSvJtKj9Ke1Bcq86zEcFg3iPIyxSY8oKK02luT3m73/0L+2BzVXzSsUwE23Nh37+jVAWt+aXHJPlg7YNJGN/9luqx90I3BiPDRtsj4AZ8OtYvBgpDbGK8cVMEDGvOg0+a8JE8oebzgzArYNlWskCRvdvVPU3rk8GKjSKDC2j5lS5sjiiT342Qc3VjoScg5pNfT5fBQ2KI3+LQW9UGwtQwX4er+rjVMM72f1BRI5pIBuwWQIQJzwlqF/KUZcCC5Ly8H8S96thxpmsnXz89GOfldFbQQa/IP5dqCERFpncg1stnDjtGUGU7LIBcBkxqC0ixHgsNKlqFkpT/2oP3y8J875sxykKcigq2Gzw8avXH0W/7nA2pGIrqMMNvMs4ORmSi0FufwNnMsmJYW/baOPUgO+yzUeWLL9wajFo7ozoXz/Q1mLhd8791XO8+ph1Txs0smqV0BK7l/8rAOfhJB1t/aLIB1D+AuVxkfFXUDCcTT4LHSpS7LgI+vsegcN5rPPdFucgMoxLncEC5Fwfww== Jeff Coffler Common Key"
 -
  username: "root"
  shadow_hash: $6$/i4bVTW/Ec/0o.eU$6BFOeP9xn4ZqoDzYbBjuZZupe9VpiqAn9wrXHmZ.Rcyyl.AxQSzmja75OOupHAuzUQ1WaI8MIUqLKdavT252t/
  ssh-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCt0tiRjcZE0XU38M6aBxaRd+fsVUnezP8/fStL4vgxuzu84FFTTK6XIVsMWVbDxROVA0H98Sexfm8ZDgxYxQ5g6Nk1wbWxB9wbPHrykJScV3tUGWh4RgDq4rm/8+k7Msd32Ubj2t5962W1h1s+zhax4io0bSvJtKj9Ke1Bcq86zEcFg3iPIyxSY8oKK02luT3m73/0L+2BzVXzSsUwE23Nh37+jVAWt+aXHJPlg7YNJGN/9luqx90I3BiPDRtsj4AZ8OtYvBgpDbGK8cVMEDGvOg0+a8JE8oebzgzArYNlWskCRvdvVPU3rk8GKjSKDC2j5lS5sjiiT342Qc3VjoScg5pNfT5fBQ2KI3+LQW9UGwtQwX4er+rjVMM72f1BRI5pIBuwWQIQJzwlqF/KUZcCC5Ly8H8S96thxpmsnXz89GOfldFbQQa/IP5dqCERFpncg1stnDjtGUGU7LIBcBkxqC0ixHgsNKlqFkpT/2oP3y8J875sxykKcigq2Gzw8avXH0W/7nA2pGIrqMMNvMs4ORmSi0FufwNnMsmJYW/baOPUgO+yzUeWLL9wajFo7ozoXz/Q1mLhd8791XO8+ph1Txs0smqV0BK7l/8rAOfhJB1t/aLIB1D+AuVxkfFXUDCcTT4LHSpS7LgI+vsegcN5rPPdFucgMoxLncEC5Fwfww== Jeff Coffler Common Key"
```

1. I can't seem to log into user `root` using the SSH key.  Examination shows that directory `/root/.ssh` does not exist.
2. I can't seem to log in to user `hanauser` using SSH key. Examination shows that directory `/home/hanauser/.ssh` is owned by root.
3. After fixing owner of `/home/hanauser/.ssh`, I still couldn't log in by key. `/home/hanauser/.ssh/authorized_keys` is also owned by root.
