### ISSUE TITLE
Credentials in the YAML file

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#6]
The YAML file currently has this segment for credentials:

```
credentials:
  username: "hanauser"
  password: "somerandompassword" (should this be base-64 encoded to allow for special characters?)
  ssh-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCt0tiRjcZE0XU38M6aBxaRd+fsVUnezP8/fStL4vgxuzu84FFTTK6XIVsMWVbDxROVA0H98Sexfm8ZDgxYxQ5g6Nk1wbWxB9wbPHrykJScV3tUGWh4RgDq4rm/8+k7Msd32Ubj2t5962W1h1s+zhax4io0bSvJtKj9Ke1Bcq86zEcFg3iPIyxSY8oKK02luT3m73/0L+2BzVXzSsUwE23Nh37+jVAWt+aXHJPlg7YNJGN/9luqx90I3BiPDRtsj4AZ8OtYvBgpDbGK8cVMEDGvOg0+a8JE8oebzgzArYNlWskCRvdvVPU3rk8GKjSKDC2j5lS5sjiiT342Qc3VjoScg5pNfT5fBQ2KI3+LQW9UGwtQwX4er+rjVMM72f1BRI5pIBuwWQIQJzwlqF/KUZcCC5Ly8H8S96thxpmsnXz89GOfldFbQQa/IP5dqCERFpncg1stnDjtGUGU7LIBcBkxqC0ixHgsNKlqFkpT/2oP3y8J875sxykKcigq2Gzw8avXH0W/7nA2pGIrqMMNvMs4ORmSi0FufwNnMsmJYW/baOPUgO+yzUeWLL9wajFo7ozoXz/Q1mLhd8791XO8+ph1Txs0smqV0BK7l/8rAOfhJB1t/aLIB1D+AuVxkfFXUDCcTT4LHSpS7LgI+vsegcN5rPPdFucgMoxLncEC5Fwfww== Jeff Coffler Common Key"
```

Anand wasn't comfortable with the raw password being in this file. His concern is that if the file is forwarded around in E-Mail, we're forwarding around credentials, which would be unfortunate.

I propose a new field in the credentials section: `password_type`. It would have three possible values:

1. plaintext: Plaintext passwords. Special characters in password (like " character) might cause problems,
2. base64: Password is Base 64 encoded, and should be decoded,
3. external: In this case, password is in an external file on the same volume as the YAML file. The `password` field would contain the name of the file (relative to /etc since that's where the YAML file is).

So, for an example with `plaintext`:

```
credentials:
  username: "hanauser"
  password: "somerandompassword"
  password_type: plaintext
```

An example with `base64`:

```
credentials:
  username: "hanauser"
  password: "c29tZXJhbmRvbXBhc3N3b3Jk"
  password_type: base64
```

Finally, an example with `external`:

```
credentials:
  username: "hanauser"
  password: "password_file"
  password_type: external
```

In this case, since `password_file` isn't an absolute path, we'd look for `/etc/password_file`, and we would expect to find something like:

```
password: "c29tZXJhbmRvbXBhc3N3b3Jk"
```

It would be assumed that any `password_type` of type `external` would always be stored in Base 64 format.

Is it possible to do this?

**Comment by theanandramakrishna** [comment]
Consider also supporting *only* external passwords, to prevent potential security incidents down the road.

**Comment by jeffaco** [comment]
I'm okay with that too. Suggestion:

```
credentials:
  username: "hanauser"
  password-file: "password_file"
  ssh-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCt0tiRjcZE0XU38M6aBxaRd+fsVUnezP8/fStL4vgxuzu84FFTTK6XIVsMWVbDxROVA0H98Sexfm8ZDgxYxQ5g6Nk1wbWxB9wbPHrykJScV3tUGWh4RgDq4rm/8+k7Msd32Ubj2t5962W1h1s+zhax4io0bSvJtKj9Ke1Bcq86zEcFg3iPIyxSY8oKK02luT3m73/0L+2BzVXzSsUwE23Nh37+jVAWt+aXHJPlg7YNJGN/9luqx90I3BiPDRtsj4AZ8OtYvBgpDbGK8cVMEDGvOg0+a8JE8oebzgzArYNlWskCRvdvVPU3rk8GKjSKDC2j5lS5sjiiT342Qc3VjoScg5pNfT5fBQ2KI3+LQW9UGwtQwX4er+rjVMM72f1BRI5pIBuwWQIQJzwlqF/KUZcCC5Ly8H8S96thxpmsnXz89GOfldFbQQa/IP5dqCERFpncg1stnDjtGUGU7LIBcBkxqC0ixHgsNKlqFkpT/2oP3y8J875sxykKcigq2Gzw8avXH0W/7nA2pGIrqMMNvMs4ORmSi0FufwNnMsmJYW/baOPUgO+yzUeWLL9wajFo7ozoXz/Q1mLhd8791XO8+ph1Txs0smqV0BK7l/8rAOfhJB1t/aLIB1D+AuVxkfFXUDCcTT4LHSpS7LgI+vsegcN5rPPdFucgMoxLncEC5Fwfww== Jeff Coffler Common Key"
```

This would look for /etc/password_file, formatted as above.

Field `password-file` is optional (no password if not specified), as is `ssh-key`. If both `password-file` and `ssh-key` are not specified, that's a good recipe for building a system that you can't log into.

**Comment by rjschwei** [comment]
The concern about e-mailing the YAML file is certainly valid if we operate in an environment where less security cautious people have access to the file.

In this environment base64 encoding is certainly no protection as a simple decode() by anyone having the yaml file reveals the plain text password.

The "external file" has a similar problem. Since the only way we have to ingest the "external file" is with either another temporary lun or alongside the YAML file. This implies that the person that has access to the YAML file for e-mailing it around also has access to the external file to e-mail it around. Therefore the external password file provides no additional protection against carelessness, obfuscation is not a security measure.

The only security is afforded if we accept the ssh key only or if we have encrypted passwords in the YAML. The later implies that the generator of the YAML file has to encrypt the password received from the user.

**Comment by jeffaco** [comment]
Encoding with base64 was never intended to be for increased security. The intent of base64 was to avoid parsing problems if the customer wanted " characters or something in the filename. By formatting the password with base64, we avoid all those issues. I even came across somebody once that put a NUL byte in his passwords (I never knew that NUL bytes could even be entered by the keyboard at the time).

In Azure today with VMs, passwords are encrypted upon entry and decrypted immediately before being used (at the very end of the process to deploy machines). But I sort of consider the YAML file to be "the end" - although if you want we can look at encryption of the password.

I think Anand's thoughts were that the YAML file might be sent in E-Mail (to discuss some section of it, say), and he didn't want password leakage from that. Of course, if an administrator is intent on using poor security practice, we can only stop that with training.

For now, I suggest we just use a base64 password in a second file, alongside with the YAML file, with the file path specified in the YAML. If the file is an absolute path, use that path; if relative, base it on location of YAML file, which is in `/etc`. This should be secure since customers can't have direct access to the NetApp to create and deploy LUNs.

Perhaps after deploying the password, the password file should be removed from the file system? This is a minor improvement, but destroys access to the plain text password before the system completes the boot process.

**Comment by rjschwei** [comment]
Sorry, I don't get it.

"YAML file might be sent in E-Mail"

Valid concern no question. Access to the YAML file is only possible for Msft or to customer/user admins that time their login just right and copy the file off the temporary lun before it gets destroyed.

For both cases where access to the temporary lun to get the YAML file is possible, since the password file exists on the same lun these groups also have access to the separate password file. Thus the password file is just as easily mailed as the YAML file.

I get the idea of considering the most obvious case of carelessness. However why would we not solve the complete problem rather than sweeping part of the problem under the rug via obfuscation?

The real solution is to either have only ssh keys or if we need to have a password put the encrypted password into the YAML. Then the problem goes away for the careless case and for the deliberate case. Given that the generator of the YAML is not in production yet one would think it should be reasonably straight forward to add an "Encrypt received password" to the design specification for the YAML generator.

**Comment by jeffaco** [comment]
I'm not adverse to solving this "right" (which would be encryption). It would simply be more work from our YAML generator (and more work on your side to decrypt the password). But that's not a problem for me if it's not a problem for you.

Note that our YAML generator will be from Go, so I may need assistance on how to encrypt/decrypt when using the Go language. I haven't done much with encryption/decryption in the past, so I might need some guidance on how to do that, exactly, from Go. And I imagine we'll need to (somehow) share certificates or shared secrets on how to encrypt/decrypt what would obviously be independent of the YAML.

**Comment by rjschwei** [comment]
We do not need to "decrypt" the password. During setup the scripts run as root and we create the user with the hashed password, the technology/process is already implemented in kiwi, we can re-use the existing solution.

The supported hashing algorithms [1] are:

$1 = MD5 hashing algorithm.
 $2 =Blowfish Algorithm is in use.
 $2a=eksblowfish Algorithm
 $5 =SHA-256 Algorithm
 $6 =SHA-512 Algorithm

where MD5 is considered weak and obsolete. [2] might help to generate the hash. Also easy for you to test.

1.) make up a string
2.) hash it with your Go code
3.) stick the result into /etc/shadow of some user account on a Linux system
4.) try to login as that user

[1] https://www.slashroot.in/how-are-passwords-stored-linux-understanding-hashing-shadow-utils
[2] https://stackoverflow.com/questions/13582519/how-to-generate-hash-number-of-a-string-in-go

**Comment by jeffaco** [comment]
Okay, so I did some testing. The first link you sent me discusses an `openssl` command that can generate Linux passwords, but strangely enough, it is *strictly* for MD5. It was never updated for newer hashing algorithms. Furthermore, the default (at least on my DEV system, Ubuntu 16) is now $6 (SHA-512). Here's the `openssl password` command example:

```
[root@slashroot1 ~]# openssl passwd -1 -salt Etg2ExUZ redhat
$1$Etg2ExUZ$F9NTP7omafhKIlqaBMqng1
[root@slashroot1 ~]#
```

I'd love some command that can just "do this" (similar to `openssl password`), but I'm not sure one exists for SHA-512.  The links you sent me gave a nice general discussion, but nothing specific on how to use the salt and hash together. Heck, the document didn't even discuss how the salt was formatted for output. Here's a sample line of output from `/etc/shadow`:

```
foo:$6$gVIklF94$V.vLSXfaXVFJr/pXqW3PCmPMxBGZDUUWbB0360Fv2pCA29nJyrhNysmA0kLW2nFxN7Tua9kW2bCpOtrD6676k.:17667:0:99999:7:::
```

So the default password format on Ubuntu 16 is SHA-512. This is an SHA-512 checksum ($6) with a salt of `gVIklF94`. What the heck is that? Base64, or something else? The document didn't discuss it, other than to say it was a salt, and why a salt is important.

Can you point me to some code (in any language) that can generate this password as formatted above? I'd love to see it to try and code it in Go. Or can you point me to a command I can run that will convert from cleartext to SHA-512 properly formatted (like `openssl password` does for MD5)?

**Comment by schaefi** [comment]
This time zone thing always let me jump in late to discussions, hope you don't mind

As Robert already said, and I agree here, the only way for increased security is to put an encrypted password into the yaml file. This is also the way we use in kiwi when people configure users as part of the kiwi XML description. There is no way (given security works) for others to decrypt that string into the original password, thus considered protected

We would take that encrypted form and create the user with it. Only people who knows the password can login with that user.

I'll go into details regarding how you can create that password string next

**Comment by schaefi** [comment]
Create your password

* The password encryption method should be SHA-512, this provides reasonable secure passwords as of today
* The salt information is a random key which makes sure the encrypted passwd string is not the same even if the password itself does not change
* You can't create SHA-512 encrypted passwords for the shadow file with the openssl command because it only supports MD5

Use the following python program to get your password:

```python
import crypt
import getpass
print(
    crypt.crypt(
        getpass.getpass(),
        crypt.mksalt(crypt.METHOD_SHA512)
    )
)
```

You can cut and paste the above and put it into a file. Given there is a python interpreter >=3.4 this also works on Windows.

Probably the go language offers crypt modules too, but frankly said there are already too many languages on the planet and python is brilliant ;)

**Comment by schaefi** [comment]
I would say the yaml file for the credentials of the user is complete with the following data:

```yaml
credentials:
  username: hanauser
  shadow_hash: $6...
```

* That also eliminates the need for base64 encoding
* I also think we should stick with one way to specify the credentials, so no alternative less secure methods

Thoughts ?

**Comment by jeffaco** [comment]
I agree with Robert's suggestion for the credentials section, see [YAML](https://gist.github.com/jeffaco/9664aa4a4e5620e7ee16c8405be03a4a).

I'm looking at coding this natively in Go, and surprisingly it's not that easy. In terms of cryptographic  strength, is $2a (eksblowfish/bcrypt) a reasonable choice? Or do you think it's important to stick with SHA-512?

**Comment by schaefi** [comment]
ok great, expect a pull request soon.

I'll open another discussion topic for the design of the package installer

**Comment by jeffaco** [comment]
I spoke to our operations team today, and they need to create multiple accounts, although some are service accounts. Also, we may need to specify UID/GID.

My thoughts:

1. Allow us to specify a UID and/or GID. If not specified, you pick (unless the "root" account),
1. Allow a list of credentials (like we do with network interfaces or disks),
1. If no password hash or public key is specified, create the account configured for no login (a service account).

I know this will affect your current PR, so I'm hoping you can update the PR to include this, or create a new PR?

Thanks.

**Comment by schaefi** [comment]
sure, no problem to update the existing PR with that additions. However I'll be on vacation next week so this one will sit a bit longer

**Comment by schaefi** [comment]
> Allow us to specify a UID and/or GID. If not specified, you pick (unless the "root" account),

Setting a group id is not recommended. The setting of the group should be done by name as their is a clear mapping of name to gid. If the group does not exist we will create it but the gid selection should be done by the system not by us.

**Comment by schaefi** [comment]
ok as it was not too much to change I added the user setup extensions to the open pull request #8. In the yaml file you can now specify the credentials as shown in the following example:

```yaml
credentials:
  -
    username: hanauser
    shadow_hash: "sha-512-cipher"
    ssh-key: "ssh-rsa foo"
  -
    username: rpc
    id: 495
    group: nogroup
    home_dir: /var/lib/empty
```
